version = 1

[[annotations]]
path = ["go.mod", "go.sum", ".envrc", "flake.lock"]
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "Unlicense"

[[annotations]]
path = ["app/.env.example"]
SPDX-FileCopyrightText = "${REUSE_COPYRIGHT}"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ["*.proto"]
SPDX-FileCopyrightText = "${REUSE_COPYRIGHT}"
SPDX-License-Identifier = "Apache-2.0"
