# SPDX-FileCopyrightText: 2025 BROKE DA EAR LLC <https://brokedaear.com>
#
# SPDX-License-Identifier: Apache-2.0

# Main application backend service configuration for the BdE website.

[directories]
log_output_dir = ""

[addresses]
database_addr = ""
