# SPDX-FileCopyrightText: 2025 BROKE DA EAR LLC <https://brokedaear.com>
#
# SPDX-License-Identifier: Apache-2.0

name: Main
on:
  push:
    branches: ["*"] # TODO change to dev later.
jobs:
  format-and-lint:
    name: Formatting and Linting
    runs-on: ubuntu-{{ vars.RUNNER_VERSION }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Check Nixpkgs inputs
        uses: DeterminateSystems/flake-checker-action@main
        with:
          fail-mode: true

      - run: nix develop --command \
          task ci-intro-text

      - name: Format all files
        run: |
          nix develop --command \
            task fmt

      - name: Lint all files
        run: |
          nix develop --command \
            task lint

  test:
    name: Unit Testing
    needs: format-and-lint
    runs-on: ubuntu-{{ vars.RUNNER_VERSION }}
    steps:
      - name: git checkout
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Unit tests
        run: |
          nix develop --command \
            task test

      - run: |
          nix develop --command \
            task ci-outro-text
