# SPDX-FileCopyrightText: 2025 BROKE DA EAR LLC <https://brokedaear.com>
#
# SPDX-License-Identifier: Apache-2.0

name: Main
on:
  push:
    branches: ["dev"]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Golangci-lint
        uses: golangci/golangci-lint-action@v6.2.0
      - name: Setup Go environment
        uses: actions/setup-go@v5.3.0
        with:
          go-version: "1.24.1"
