# SPDX-FileCopyrightText: 2025 BROKE DA EAR LLC <https://brokedaear.com>
#
# SPDX-License-Identifier: Apache-2.0

name: Main
on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]
jobs:
  check-flake:
    name: Check Nix flake
    runs-on: ubuntu-${{ vars.RUNNER_VERSION }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31.4.0
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v16
        with:
          name: brokedaear
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix flake check --print-build-logs

      - name: Lint and Test
        run: nix develop .#ci --profile ci-env -c run-ci

      # - name: Update cache
      #   if: success()
      #   env:
      #     CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
      #   run: cachix push brokedaear ci-env

      # - name: Install Nix
      #   uses: DeterminateSystems/nix-installer-action@main
      # - uses: DeterminateSystems/flakehub-cache-action@main
      # - name: Check Nixpkgs inputs
      #   uses: DeterminateSystems/flake-checker-action@main
      #   with:
      #     fail-mode: true

  # lint-and-test:
  #   name: Formatting and Linting
  #   runs-on: ubuntu-${{ vars.RUNNER_VERSION }}
  #   needs: check-flake
  #   steps:
  #       uses: actions/checkout@v4
  #     - name: Install Nix
  #       uses: DeterminateSystems/nix-installer-action@main
  #     - uses: DeterminateSystems/flakehub-cache-action@main
  #
  #     - name: Lint and Test
  #       run: nix develop .#ci --command run-ci
