# SPDX-FileCopyrightText: 2025 BROKE DA EAR LLC <https://brokedaear.com>
#
# SPDX-License-Identifier: Apache-2.0

name: Main
on:
  push:
    branches: ["*"] # TODO change to dev later.
jobs:
  check-flake:
    name: Check Nix flake
    runs-on: ubuntu-${{ vars.RUNNER_VERSION }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/flakehub-cache-action@main
      - name: Check Nixpkgs inputs
        uses: DeterminateSystems/flake-checker-action@main
        with:
          fail-mode: true

      - name: Check flake
        run: nix flake check

  format-and-lint:
    name: Formatting and Linting
    runs-on: ubuntu-${{ vars.RUNNER_VERSION }}
    needs: check-flake
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/flakehub-cache-action@main
      - name: Check Nixpkgs inputs
        uses: DeterminateSystems/flake-checker-action@main
        with:
          fail-mode: true

      - name: Run CI script
        run: nix develop --command \
          ./scripts/ci.sh

